2021-03-12 17:07:47,881 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-12 17:07:47,884 aiogram - WARNING:Goodbye!
2021-03-12 17:07:55,241 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-12 17:07:56,514 aiogram - WARNING:Updates were skipped successfully.
2021-03-12 17:07:56,519 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-12 17:09:44,576 handlers.auth - INFO:Новый пользователь.
2021-03-12 17:09:54,559 handlers.auth - INFO:1037171446 used the command /group_list
2021-03-12 17:10:06,572 handlers.auth - INFO:1037171446 changed the group
2021-03-12 17:10:25,515 handlers.auth - INFO:1037171446 created a new group
2021-03-12 17:10:39,413 handlers.member - INFO:1037171446 leave_group: ИБ
2021-03-12 17:10:51,721 handlers.auth - INFO:1037171446 changed the group
2021-03-12 17:10:53,555 handlers.auth - INFO:553818543 changed the group
2021-03-12 17:10:54,575 handlers.member - INFO:1037171446 used the command /help
2021-03-12 17:10:57,873 handlers.member - INFO:553818543 learned homework
2021-03-12 17:10:58,366 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:11:09,234 handlers.member - INFO:553818543 learned homework
2021-03-12 17:11:21,523 handlers.member - INFO:553818543 used the command /subjects
2021-03-12 17:11:33,459 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:11:45,533 handlers.member - INFO:1037171446 used the command /group_name
2021-03-12 17:11:49,302 handlers.auth - INFO:1037171446 used the command /group_list
2021-03-12 17:11:49,944 handlers.auth - INFO:553818543 used the command /group_list
2021-03-12 17:11:54,503 handlers.member - INFO:1037171446 used the command /subjects
2021-03-12 17:13:27,777 handlers.member - INFO:1037171446 leave_group: ИБ 2 курс
2021-03-12 17:13:46,370 handlers.auth - INFO:1037171446 created a new group
2021-03-12 17:15:02,679 handlers.member - INFO:553818543 found out the schedule
2021-03-12 17:15:13,860 handlers.auth - INFO:1037171446 used the command /group_list
2021-03-12 17:15:14,818 handlers.member - INFO:553818543 found out the schedule
2021-03-12 17:16:05,676 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-240' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/headman.py", line 119, in send_add_file
    photo = open('help_photo\help_for_add_file.jpg','rb')
FileNotFoundError: [Errno 2] No such file or directory: 'help_photo\\help_for_add_file.jpg'
2021-03-12 17:16:12,138 handlers.headman - INFO:%s is dumb
2021-03-12 17:16:17,047 handlers.headman - INFO:%s is dumb
2021-03-12 17:16:25,038 handlers.headman - INFO:%s is dumb
2021-03-12 17:16:30,259 handlers.headman - INFO:%s is dumb
2021-03-12 17:16:35,165 handlers.headman - INFO:%s is dumb
2021-03-12 17:17:00,883 handlers.member - INFO:1037171446 used the command /subjects
2021-03-12 17:17:59,004 handlers.member - INFO:1037171446 leave_group: Иб
2021-03-12 17:18:09,779 handlers.auth - INFO:1037171446 changed the group
2021-03-12 17:18:11,933 handlers.member - INFO:1037171446 used the command /help
2021-03-12 17:19:42,184 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:21:35,232 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:21:54,051 handlers.member - INFO:1037171446 used the command /subjects
2021-03-12 17:22:01,430 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:22:18,315 handlers.member - INFO:553818543 used the command /help
2021-03-12 17:23:13,935 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:23:17,769 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:23:26,522 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:23:50,470 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:25:35,362 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:25:43,952 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:25:45,183 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:25:46,388 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:25:47,557 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:26:14,857 handlers.admin - INFO:1037171446 sent me a message
2021-03-12 17:26:46,503 handlers.admin - INFO:I replied to someone's message.
2021-03-12 17:29:54,504 handlers.admin - INFO:1037171446 sent me a message
2021-03-12 17:30:21,559 handlers.admin - INFO:I replied to someone's message.
2021-03-12 17:30:43,010 handlers.member - INFO:1037171446 found out the schedule
2021-03-12 17:30:48,279 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:30:54,117 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:30:56,258 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-537' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/headman.py", line 119, in send_add_file
    photo = open('help_photo\help_for_add_file.jpg','rb')
FileNotFoundError: [Errno 2] No such file or directory: 'help_photo\\help_for_add_file.jpg'
2021-03-12 17:31:35,270 handlers.headman - INFO:%s is dumb
2021-03-12 17:31:55,832 handlers.headman - INFO:553818543 created a new homework with files
2021-03-12 17:32:08,890 handlers.member - INFO:553818543 found out the schedule
2021-03-12 17:32:08,947 handlers.member - INFO:1037171446 learned homework
2021-03-12 17:32:15,831 handlers.member - INFO:553818543 learned homework
2021-03-12 17:35:39,789 handlers.member - INFO:553818543 learned homework
2021-03-12 17:40:33,802 handlers.member - INFO:553818543 used the command /help
2021-03-12 17:41:53,192 handlers.auth - INFO:Новый пользователь.
2021-03-12 17:42:11,925 handlers.auth - INFO:665754238 used the command /group_list
2021-03-12 17:42:19,477 handlers.auth - INFO:665754238 changed the group
2021-03-12 17:42:28,397 handlers.auth - INFO:665754238 created a new group
2021-03-12 17:46:34,128 handlers.member - INFO:665754238 leave_group: Хуи
2021-03-12 17:46:43,010 handlers.auth - INFO:665754238 changed the group
2021-03-12 17:47:10,723 handlers.member - INFO:665754238 used the command /help
2021-03-12 17:47:15,009 handlers.member - INFO:665754238 used the command /subjects
2021-03-12 17:49:20,346 handlers.member - INFO:665754238 learned homework
2021-03-12 17:58:23,914 handlers.auth - INFO:553818543 used the command /group_list
2021-03-12 18:31:25,398 handlers.member - INFO:553818543 found out the schedule
2021-03-12 18:55:46,231 handlers.member - INFO:1037171446 used the command /subjects
2021-03-12 18:56:16,082 handlers.member - INFO:1037171446 learned homework
2021-03-12 21:00:33,427 handlers.member - INFO:553818543 used the command /help
2021-03-12 21:00:38,483 handlers.member - INFO:553818543 found out the schedule
2021-03-12 23:10:38,371 handlers.member - INFO:553818543 found out the schedule
2021-03-12 23:11:11,118 handlers.member - INFO:553818543 used the command /subjects
2021-03-12 23:11:29,814 handlers.member - INFO:553818543 learned homework
2021-03-13 01:02:23,945 handlers.member - INFO:553818543 found out the schedule
2021-03-13 01:03:32,616 handlers.member - INFO:553818543 learned homework
2021-03-13 07:50:11,064 handlers.member - INFO:553818543 found out the schedule
2021-03-13 08:25:32,890 handlers.member - INFO:1037171446 learned homework
2021-03-13 09:24:02,759 handlers.auth - INFO:Новый пользователь.
2021-03-13 09:24:33,739 handlers.auth - INFO:354644572 used the command /group_list
2021-03-13 09:29:48,292 handlers.auth - INFO:Новый пользователь.
2021-03-13 09:30:04,583 handlers.auth - INFO:495019014 used the command /group_list
2021-03-13 09:30:58,215 handlers.auth - INFO:495019014 changed the group
2021-03-13 09:31:02,086 handlers.member - INFO:495019014 used the command /help
2021-03-13 09:31:29,245 handlers.member - INFO:495019014 leave_group: ИБ
2021-03-13 09:32:27,454 handlers.auth - INFO:Новый пользователь.
2021-03-13 09:33:39,169 handlers.auth - INFO:1073175394 changed the group
2021-03-13 09:33:42,571 handlers.member - INFO:1073175394 used the command /help
2021-03-13 09:37:48,037 handlers.member - INFO:1073175394 used the command /subjects
2021-03-13 09:42:10,801 handlers.auth - INFO:Новый пользователь.
2021-03-13 09:42:35,070 handlers.auth - INFO:540553756 used the command /group_list
2021-03-13 09:42:44,476 handlers.auth - INFO:540553756 changed the group
2021-03-13 09:42:55,843 handlers.auth - INFO:540553756 created a new group
2021-03-13 09:43:11,211 handlers.member - INFO:540553756 used the command /subjects
2021-03-13 10:07:33,063 handlers.auth - INFO:Новый пользователь.
2021-03-13 10:08:20,169 handlers.auth - INFO:381053002 changed the group
2021-03-13 10:08:31,062 handlers.auth - INFO:381053002 used the command /group_list
2021-03-13 10:08:39,213 handlers.member - INFO:381053002 used the command /help
2021-03-13 10:08:56,565 handlers.member - INFO:381053002 found out the schedule
2021-03-13 10:09:11,498 handlers.member - INFO:381053002 used the command /subjects
2021-03-13 10:42:06,309 handlers.auth - INFO:Новый пользователь.
2021-03-13 10:42:25,096 handlers.auth - INFO:408808247 changed the group
2021-03-13 10:42:29,548 handlers.member - INFO:408808247 used the command /help
2021-03-13 10:46:54,160 handlers.auth - INFO:Новый пользователь.
2021-03-13 10:47:16,433 handlers.auth - INFO:1093401987 changed the group
2021-03-13 10:47:18,610 handlers.member - INFO:1093401987 used the command /help
2021-03-13 12:08:53,382 handlers.auth - INFO:Новый пользователь.
2021-03-13 12:09:33,641 handlers.auth - INFO:1003894317 used the command /group_list
2021-03-13 13:55:35,170 handlers.auth - INFO:Новый пользователь.
2021-03-13 13:55:58,397 handlers.auth - INFO:983872632 changed the group
2021-03-13 13:56:04,549 handlers.member - INFO:983872632 used the command /help
2021-03-13 13:56:15,738 handlers.member - INFO:983872632 found out the schedule
2021-03-13 13:56:26,988 handlers.member - INFO:983872632 used the command /subjects
2021-03-13 16:47:46,433 handlers.member - INFO:553818543 found out the schedule
2021-03-13 16:48:14,203 handlers.member - INFO:553818543 used the command /group_name
2021-03-13 18:10:02,609 handlers.auth - INFO:Новый пользователь.
2021-03-13 18:26:40,945 handlers.member - INFO:553818543 found out the schedule
2021-03-13 18:26:56,770 handlers.member - INFO:553818543 used the command /help
2021-03-13 19:29:51,054 handlers.admin - INFO:553818543 sent me a message
2021-03-13 22:32:01,815 handlers.admin - INFO:I made a mailing
2021-03-13 22:32:02,393 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-6244' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BotBlocked('Forbidden: bot was blocked by the user')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 19, in wrapper
    return await func(message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 31, in mailing
    await bot.send_message(member_id, answer_message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 121, in check_result
    exceptions.Unauthorized.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.BotBlocked: Forbidden: bot was blocked by the user
2021-03-13 22:33:55,902 handlers.admin - INFO:I made a mailing
2021-03-13 22:33:56,469 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-6261' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BotBlocked('Forbidden: bot was blocked by the user')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 19, in wrapper
    return await func(message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 31, in mailing
    await bot.send_message(member_id, answer_message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 121, in check_result
    exceptions.Unauthorized.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.BotBlocked: Forbidden: bot was blocked by the user
2021-03-13 22:34:20,480 handlers.admin - INFO:553818543 sent me a message
2021-03-13 22:38:50,515 handlers.admin - INFO:I made a mailing
2021-03-13 22:38:51,081 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-6296' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BotBlocked('Forbidden: bot was blocked by the user')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 19, in wrapper
    return await func(message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 31, in mailing
    await bot.send_message(member_id, answer_message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 121, in check_result
    exceptions.Unauthorized.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.BotBlocked: Forbidden: bot was blocked by the user
2021-03-13 22:39:01,552 handlers.admin - INFO:408808247 sent me a message
2021-03-13 22:39:17,752 handlers.admin - INFO:408808247 sent me a message
2021-03-13 22:39:30,142 handlers.admin - INFO:408808247 sent me a message
2021-03-13 22:39:42,750 handlers.admin - INFO:408808247 sent me a message
2021-03-13 22:40:11,305 handlers.admin - INFO:I replied to someone's message.
2021-03-13 22:43:14,097 handlers.auth - INFO:553818543 changed the group
2021-03-13 22:43:19,100 handlers.member - INFO:553818543 used the command /help
2021-03-13 22:43:22,080 handlers.member - INFO:553818543 used the command /subjects
2021-03-13 22:43:41,013 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-6386' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=FileNotFoundError(2, 'No such file or directory')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/headman.py", line 119, in send_add_file
    photo = open('help_photo\help_for_add_file.jpg','rb')
FileNotFoundError: [Errno 2] No such file or directory: 'help_photo\\help_for_add_file.jpg'
2021-03-13 22:47:27,428 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-13 22:47:27,431 aiogram - WARNING:Goodbye!
2021-03-13 23:14:38,491 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-13 23:14:39,990 aiogram - WARNING:Updates were skipped successfully.
2021-03-13 23:14:39,995 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-13 23:15:06,105 handlers.auth - INFO:553818543 changed the group
2021-03-13 23:15:07,457 handlers.member - INFO:553818543 used the command /help
2021-03-13 23:15:28,230 handlers.admin - INFO:I made a mailing
2021-03-13 23:15:28,817 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=BotBlocked('Forbidden: bot was blocked by the user')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 19, in wrapper
    return await func(message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/admin.py", line 31, in mailing
    await bot.send_message(member_id, answer_message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 318, in send_message
    result = await self.request(api.Methods.SEND_MESSAGE, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 121, in check_result
    exceptions.Unauthorized.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.BotBlocked: Forbidden: bot was blocked by the user
2021-03-13 23:15:42,675 handlers.member - INFO:553818543 used the command /help
2021-03-13 23:27:03,301 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-13 23:27:03,304 aiogram - WARNING:Goodbye!
2021-03-13 23:35:30,687 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-13 23:35:32,147 aiogram - WARNING:Updates were skipped successfully.
2021-03-13 23:35:32,149 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-13 23:35:57,684 handlers.auth - INFO:553818543 changed the group
2021-03-13 23:39:54,391 handlers.admin - INFO:I made a mailing
2021-03-13 23:40:51,329 handlers.member - INFO:553818543 used the command /group_name
2021-03-13 23:48:54,865 handlers.admin - INFO:553818543 sent me a message
2021-03-14 00:04:32,596 handlers.auth - INFO:665754238 changed the group
2021-03-14 00:04:40,741 handlers.admin - INFO:665754238 sent me a message
2021-03-14 00:04:52,655 handlers.admin - INFO:665754238 sent me a message
2021-03-14 00:06:15,243 handlers.admin - INFO:I replied to someone's message.
2021-03-14 00:08:21,927 handlers.admin - INFO:I replied to someone's message.
2021-03-14 00:10:49,755 handlers.member - INFO:553818543 used the command /group_name
2021-03-14 00:54:33,528 handlers.auth - INFO:540553756 changed the group
2021-03-14 00:54:36,280 handlers.member - INFO:540553756 used the command /help
2021-03-14 00:54:44,882 handlers.member - INFO:540553756 used the command /subjects
2021-03-14 00:55:04,342 handlers.member - INFO:540553756 found out the schedule
2021-03-14 00:55:47,547 handlers.admin - INFO:540553756 sent me a message
2021-03-14 00:56:19,184 handlers.admin - INFO:I replied to someone's message.
2021-03-14 00:57:37,701 handlers.admin - INFO:540553756 sent me a message
2021-03-14 00:57:57,711 handlers.admin - INFO:540553756 sent me a message
2021-03-14 00:58:51,558 handlers.admin - INFO:I replied to someone's message.
2021-03-14 00:59:38,260 handlers.member - INFO:553818543 used the command /help
2021-03-14 01:53:29,537 handlers.member - INFO:553818543 found out the schedule
2021-03-14 07:32:08,374 handlers.auth - INFO:1073175394 changed the group
2021-03-14 07:32:12,057 handlers.member - INFO:1073175394 used the command /help
2021-03-14 07:32:20,161 handlers.member - INFO:1073175394 found out the schedule
2021-03-14 12:13:09,642 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-14 12:13:09,644 aiogram - WARNING:Goodbye!
2021-03-14 12:21:15,674 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-14 12:21:15,889 aiogram - WARNING:Updates were skipped successfully.
2021-03-14 12:21:15,890 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-14 12:21:49,280 handlers.auth - INFO:553818543 changed the group
2021-03-14 12:21:53,120 handlers.member - INFO:553818543 found out the schedule
2021-03-14 12:22:03,025 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-14 12:22:03,029 aiogram - WARNING:Goodbye!
2021-03-14 12:29:11,707 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-14 12:29:13,166 aiogram - WARNING:Updates were skipped successfully.
2021-03-14 12:29:13,169 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-14 12:29:38,997 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-14 12:29:40,828 handlers.member - INFO:553818543 used the command /help
2021-03-14 12:29:47,108 handlers.member - INFO:553818543 found out the schedule
2021-03-14 12:29:52,906 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-14 12:29:52,910 aiogram - WARNING:Goodbye!
2021-03-14 12:30:07,312 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-14 12:30:08,786 aiogram - WARNING:Updates were skipped successfully.
2021-03-14 12:30:08,787 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-14 12:31:35,554 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-14 12:31:35,557 aiogram - WARNING:Goodbye!
2021-03-14 12:36:10,549 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-14 12:36:11,897 aiogram - WARNING:Updates were skipped successfully.
2021-03-14 12:36:11,903 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-14 12:36:23,890 handlers.auth - INFO:553818543 changed the group to: /tmr
2021-03-14 12:36:36,785 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-14 12:36:40,228 handlers.member - INFO:553818543 found out the schedule
2021-03-14 12:37:06,506 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-14 12:37:06,509 aiogram - WARNING:Goodbye!
2021-03-14 12:37:43,366 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-14 12:37:44,668 aiogram - WARNING:Updates were skipped successfully.
2021-03-14 12:37:44,671 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-14 12:38:01,565 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-14 12:38:04,680 handlers.member - INFO:553818543 found out the schedule
2021-03-14 12:40:00,132 handlers.admin - INFO:I made a mailing: /mailing надо было пофиксить ошибку при которой присылалось не правильное расписание из за чего пришлось выключить бота введите команду /connect и подключитесь к группе: "ИБ 2 курс"
2021-03-14 12:40:18,116 handlers.member - INFO:553818543 found out the schedule
2021-03-14 12:50:16,711 handlers.auth - INFO:665754238 changed the group to: ИБ 2 курс
2021-03-14 12:50:34,521 handlers.admin - INFO:665754238 sent me a message
2021-03-14 12:53:09,659 handlers.admin - INFO:I replied to someone's message.
2021-03-14 13:09:58,191 handlers.auth - INFO:408808247 changed the group to: Иб
2021-03-14 13:10:00,984 handlers.member - INFO:408808247 used the command /help
2021-03-14 13:10:09,337 handlers.member - INFO:408808247 used the command /subjects
2021-03-14 14:21:07,709 handlers.auth - INFO:1003894317 changed the group to: ИБ 2
2021-03-14 14:21:20,926 handlers.auth - INFO:1003894317 changed the group to: ИБ 2 курс
2021-03-14 14:21:25,837 handlers.member - INFO:1003894317 used the command /help
2021-03-14 14:21:33,356 handlers.member - INFO:1003894317 found out the schedule
2021-03-14 14:21:56,545 handlers.member - INFO:1003894317 used the command /subjects
2021-03-14 14:39:10,600 handlers.auth - INFO:1073175394 changed the group to: ИБ 2 курс
2021-03-14 14:39:12,450 handlers.member - INFO:1073175394 used the command /help
2021-03-14 14:39:16,516 handlers.member - INFO:1073175394 found out the schedule
2021-03-14 15:58:14,951 handlers.member - INFO:553818543 found out the schedule
2021-03-14 16:06:22,001 handlers.auth - INFO:1037171446 changed the group to: ИБ 2 КУРС
2021-03-14 16:06:28,998 handlers.auth - INFO:1037171446 changed the group to: ИБ 2 курс
2021-03-14 16:06:30,797 handlers.member - INFO:1037171446 used the command /help
2021-03-14 16:06:33,919 handlers.member - INFO:1037171446 found out the schedule
2021-03-14 16:07:22,155 handlers.member - INFO:1037171446 learned homework
2021-03-14 16:34:46,455 handlers.auth - INFO:Новый пользователь.
2021-03-14 16:34:59,732 handlers.auth - INFO:512893391 used the command /group_list
2021-03-14 16:54:14,424 handlers.member - INFO:553818543 found out the schedule
2021-03-14 17:22:34,952 handlers.auth - INFO:540553756 changed the group to: Иб 2 курс
2021-03-14 17:31:50,286 handlers.member - INFO:553818543 found out the schedule
2021-03-14 17:31:54,807 handlers.member - INFO:553818543 found out the schedule
2021-03-14 17:32:12,797 handlers.member - INFO:553818543 learned homework
2021-03-14 17:50:41,364 handlers.member - INFO:553818543 used the command /help
2021-03-14 17:50:47,937 handlers.auth - INFO:553818543 changed the group to: cc
2021-03-14 17:50:49,487 handlers.member - INFO:553818543 used the command /help
2021-03-14 17:51:28,516 handlers.headman - INFO:553818543 created a new homework with files
2021-03-14 17:51:34,028 handlers.member - INFO:553818543 learned homework
2021-03-14 17:51:45,083 handlers.member - INFO:553818543 learned homework
2021-03-14 18:40:01,036 handlers.auth - INFO:553818543 created a new group: Абдула
2021-03-14 18:40:40,420 handlers.headman - INFO:%s created a new subject
2021-03-14 18:40:46,226 handlers.member - INFO:553818543 used the command /subjects
2021-03-14 18:41:40,622 handlers.headman - INFO:553818543 created a new homework with files
2021-03-14 18:41:57,205 handlers.member - INFO:553818543 learned homework
2021-03-14 18:42:02,417 handlers.member - INFO:553818543 learned homework
2021-03-14 18:42:06,109 handlers.member - INFO:553818543 learned homework
2021-03-14 18:44:55,066 handlers.member - INFO:553818543 used the command /help
2021-03-14 18:44:58,689 handlers.member - INFO:553818543 found out the schedule
2021-03-14 18:45:50,371 handlers.admin - INFO:553818543 sent me a message
2021-03-14 18:46:10,635 handlers.admin - INFO:I replied to someone's message.
2021-03-14 18:51:35,915 handlers.auth - INFO:553818543 used the command /group_list
2021-03-14 19:41:00,132 handlers.auth - INFO:983872632 changed the group to: ИБ 2 курс
2021-03-14 19:41:02,355 handlers.member - INFO:983872632 used the command /help
2021-03-14 19:41:12,024 handlers.auth - INFO:983872632 used the command /group_list
2021-03-14 19:41:19,722 handlers.member - INFO:983872632 found out the schedule
2021-03-14 23:42:39,059 handlers.auth - INFO:1003894317 used the command /group_list
2021-03-15 00:14:27,825 handlers.auth - INFO:553818543 used the command /group_list
2021-03-15 00:14:34,169 handlers.member - INFO:553818543 found out the schedule
2021-03-15 00:14:51,242 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-15 00:14:53,092 handlers.member - INFO:553818543 used the command /help
2021-03-15 00:15:03,444 handlers.member - INFO:553818543 found out the schedule
2021-03-15 00:15:05,204 handlers.member - INFO:553818543 found out the schedule
2021-03-15 00:15:14,599 handlers.member - INFO:553818543 learned homework
2021-03-15 00:58:06,609 handlers.member - INFO:553818543 found out the schedule
2021-03-15 03:18:20,243 handlers.member - INFO:665754238 found out the schedule
2021-03-15 03:18:30,406 handlers.member - INFO:665754238 found out the schedule
2021-03-15 03:20:02,747 handlers.admin - INFO:665754238 sent me a message
2021-03-15 03:22:18,495 handlers.admin - INFO:I replied to someone's message.
2021-03-15 09:49:54,066 handlers.member - INFO:1003894317 found out the schedule
2021-03-15 12:10:51,479 handlers.member - INFO:983872632 found out the schedule
2021-03-15 15:24:47,994 handlers.member - INFO:553818543 used the command /help
2021-03-15 16:58:06,740 handlers.auth - INFO:Новый пользователь.
2021-03-15 16:58:55,278 handlers.auth - INFO:516235134 used the command /group_list
2021-03-15 16:59:14,876 handlers.auth - INFO:516235134 changed the group to: ПИМ 3
2021-03-15 16:59:40,603 handlers.auth - INFO:516235134 changed the group to: Пиздец
2021-03-15 17:29:13,629 handlers.auth - INFO:Новый пользователь.
2021-03-15 17:29:40,810 handlers.auth - INFO:938882970 changed the group to: ПИЭ
2021-03-15 17:29:43,754 handlers.auth - INFO:938882970 used the command /group_list
2021-03-15 17:31:14,216 handlers.auth - INFO:938882970 created a new group: Сагърай лезгияр
2021-03-15 17:33:58,115 handlers.auth - INFO:Новый пользователь.
2021-03-15 17:34:17,470 handlers.auth - INFO:1407490569 used the command /group_list
2021-03-15 17:34:35,735 handlers.auth - INFO:1407490569 changed the group to: ИСиП
2021-03-15 17:34:41,545 handlers.auth - INFO:1407490569 changed the group to: ESeP
2021-03-15 17:34:49,350 handlers.auth - INFO:1407490569 changed the group to: esep
2021-03-15 17:35:10,744 handlers.auth - INFO:1407490569 changed the group to: ISiP
2021-03-15 17:35:29,851 handlers.auth - INFO:553818543 changed the group to: ПИМ
2021-03-15 17:35:38,972 handlers.auth - INFO:553818543 changed the group to: ПИЭ 3
2021-03-15 17:37:04,005 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-15 17:37:04,007 aiogram - WARNING:Goodbye!
2021-03-15 17:42:12,296 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-15 17:42:12,481 aiogram - WARNING:Updates were skipped successfully.
2021-03-15 17:42:12,483 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-15 17:42:12,799 handlers.auth - INFO:Новый пользователь.
2021-03-15 17:42:33,870 handlers.auth - INFO:553818543 changed the group to: Оод
2021-03-15 17:42:55,101 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-15 17:42:55,106 aiogram - WARNING:Goodbye!
2021-03-15 17:43:59,964 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-15 17:44:01,289 aiogram - WARNING:Updates were skipped successfully.
2021-03-15 17:44:01,290 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-15 17:44:05,375 handlers.auth - INFO:553818543 changed the group to: Одд
2021-03-15 17:49:05,038 handlers.auth - INFO:Новый пользователь.
2021-03-15 17:49:16,301 handlers.auth - INFO:447335314 used the command /group_list
2021-03-15 17:56:14,050 handlers.auth - INFO:553818543 changed the group to: /mailing Многие заходят в бота, пытаются присоединиться к группе, получают ответа такой группы нет и уходят. Если вашей группы нет попросите старосту ее создать и скинуть вам ее название. Если бот не реагирует на команды то скорее всего проходили технические работы и бот отключался, в таком случае достаточно ввести команду /connect и присоединится к вашей группе. Со всеми вопросами обращайтесь /devlop_pituh или мне в личку 89634267274
2021-03-15 17:56:29,940 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-15 17:56:34,838 handlers.admin - INFO:I made a mailing: /mailing Многие заходят в бота, пытаются присоединиться к группе, получают ответа такой группы нет и уходят. Если вашей группы нет попросите старосту ее создать и скинуть вам ее название. Если бот не реагирует на команды то скорее всего проходили технические работы и бот отключался, в таком случае достаточно ввести команду /connect и присоединится к вашей группе. Со всеми вопросами обращайтесь /devlop_pituh или мне в личку 89634267274
2021-03-15 17:58:49,468 handlers.member - INFO:553818543 used the command /help
2021-03-15 17:58:52,990 handlers.member - INFO:553818543 found out the schedule
2021-03-15 17:58:55,738 handlers.member - INFO:553818543 found out the schedule
2021-03-15 18:05:16,025 handlers.auth - INFO:Новый пользователь.
2021-03-15 18:05:25,594 handlers.auth - INFO:366447625 used the command /group_list
2021-03-15 18:05:33,693 handlers.auth - INFO:Новый пользователь.
2021-03-15 18:06:00,725 handlers.auth - INFO:596332689 changed the group to: ИСиП
2021-03-15 18:06:02,594 handlers.auth - INFO:Новый пользователь.
2021-03-15 18:07:09,211 handlers.auth - INFO:665754238 changed the group to: ИБ 2 курс
2021-03-15 18:07:12,352 handlers.auth - INFO:Новый пользователь.
2021-03-15 18:07:12,612 handlers.member - INFO:665754238 found out the schedule
2021-03-15 18:07:40,410 handlers.auth - INFO:455441547 used the command /group_list
2021-03-15 18:07:40,590 handlers.auth - INFO:455441547 used the command /group_list
2021-03-15 18:07:50,444 handlers.member - INFO:665754238 used the command /help
2021-03-15 18:08:05,120 handlers.auth - INFO:455441547 changed the group to: Единая Россия
2021-03-15 18:08:22,343 handlers.auth - INFO:455441547 created a new group: Единая Россия
2021-03-15 18:08:53,983 handlers.member - INFO:665754238 used the command /subjects
2021-03-15 18:16:37,428 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-15 18:16:37,431 aiogram - WARNING:Goodbye!
2021-03-15 18:16:50,931 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-15 18:16:52,162 aiogram - WARNING:Updates were skipped successfully.
2021-03-15 18:16:52,166 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-15 18:17:24,893 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-15 18:17:24,896 aiogram - WARNING:Goodbye!
2021-03-15 18:17:42,446 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-15 18:17:43,892 aiogram - WARNING:Updates were skipped successfully.
2021-03-15 18:17:43,897 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-15 18:17:56,508 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-15 18:18:08,219 handlers.member - INFO:553818543 learned homework
2021-03-15 18:37:11,914 handlers.member - INFO:553818543 used the command /help
2021-03-15 18:37:15,683 handlers.member - INFO:553818543 found out the schedule
2021-03-15 18:37:18,133 handlers.member - INFO:553818543 found out the schedule
2021-03-15 18:55:02,214 handlers.auth - INFO:Новый пользователь.
2021-03-15 18:55:53,622 handlers.auth - INFO:868841570 used the command /group_list
2021-03-15 20:52:02,780 handlers.auth - INFO:Новый пользователь.
2021-03-15 22:19:45,349 handlers.auth - INFO:540553756 changed the group to: ИБ 2 курс
2021-03-15 22:19:48,735 handlers.member - INFO:540553756 used the command /help
2021-03-15 22:19:52,849 handlers.member - INFO:540553756 found out the schedule
2021-03-15 22:50:43,632 handlers.admin - INFO:540553756 sent me a message
2021-03-15 22:52:48,953 handlers.admin - INFO:I replied to someone's message.
2021-03-15 22:53:05,548 handlers.admin - INFO:540553756 sent me a message
2021-03-15 22:53:25,206 handlers.admin - INFO:I replied to someone's message.
2021-03-16 00:49:10,308 handlers.member - INFO:553818543 found out the schedule
2021-03-16 08:27:10,911 handlers.auth - INFO:983872632 changed the group to: /now
2021-03-16 08:27:15,946 handlers.auth - INFO:983872632 used the command /group_list
2021-03-16 08:27:23,502 handlers.auth - INFO:983872632 changed the group to: Иб 2 курс
2021-03-16 08:27:33,334 handlers.auth - INFO:983872632 changed the group to: ИБ 2 курс
2021-03-16 08:27:36,714 handlers.member - INFO:983872632 used the command /help
2021-03-16 08:27:39,612 handlers.member - INFO:983872632 found out the schedule
2021-03-16 10:48:30,439 handlers.auth - INFO:Новый пользователь.
2021-03-16 12:00:40,257 handlers.member - INFO:553818543 found out the schedule
2021-03-16 12:01:05,663 handlers.member - INFO:553818543 found out the schedule
2021-03-16 12:08:52,296 handlers.member - INFO:983872632 found out the schedule
2021-03-16 12:23:34,438 handlers.member - INFO:553818543 used the command /help
2021-03-16 12:23:37,217 handlers.member - INFO:553818543 used the command /subjects
2021-03-16 13:07:01,056 handlers.member - INFO:553818543 used the command /subjects
2021-03-16 13:23:34,527 handlers.member - INFO:553818543 used the command /help
2021-03-16 13:47:07,999 handlers.headman - INFO:553818543 created a new homework without files
2021-03-16 13:48:55,190 handlers.headman - INFO:553818543 created a new homework without files
2021-03-16 13:49:03,189 handlers.member - INFO:553818543 learned homework
2021-03-16 13:49:09,950 handlers.member - INFO:553818543 learned homework
2021-03-16 14:15:02,150 handlers.auth - INFO:Новый пользователь.
2021-03-16 14:15:22,661 handlers.auth - INFO:564689077 used the command /group_list
2021-03-16 14:15:53,546 handlers.auth - INFO:564689077 used the command /group_list
2021-03-16 15:18:11,612 handlers.auth - INFO:Новый пользователь.
2021-03-16 15:18:24,006 handlers.auth - INFO:467280224 used the command /group_list
2021-03-16 15:18:31,777 handlers.auth - INFO:467280224 changed the group to: ПИЭ
2021-03-16 15:24:42,032 handlers.member - INFO:553818543 learned homework
2021-03-16 15:24:54,626 handlers.member - INFO:553818543 learned homework
2021-03-16 16:58:45,319 handlers.auth - INFO:665754238 changed the group to: ИБ 2 курс
2021-03-16 16:59:22,137 handlers.admin - INFO:665754238 sent me a message
2021-03-16 16:59:49,992 handlers.member - INFO:665754238 found out the schedule
2021-03-16 16:59:56,609 handlers.admin - INFO:I replied to someone's message.
2021-03-16 17:02:17,016 handlers.admin - INFO:665754238 sent me a message
2021-03-16 17:05:44,088 handlers.admin - INFO:I replied to someone's message.
2021-03-16 17:12:07,397 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 17:12:07,400 aiogram - WARNING:Goodbye!
2021-03-16 17:12:32,622 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 17:12:33,825 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 17:12:33,830 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 17:13:11,942 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 17:14:19,769 handlers.auth - INFO:665754238 changed the group to: ИБ 2 курс
2021-03-16 18:37:58,014 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:37:58,017 aiogram - WARNING:Goodbye!
2021-03-16 18:41:16,921 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:41:18,288 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:41:18,290 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:41:30,878 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:41:36,716 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:41:43,799 handlers.auth - INFO:553818543 created a new group: Лол
2021-03-16 18:41:47,484 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-24' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:41:55,982 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:41:55,985 aiogram - WARNING:Goodbye!
2021-03-16 18:48:21,955 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:48:23,309 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:48:23,320 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:48:33,904 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:48:38,520 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-12' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:48:41,279 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:48:47,742 handlers.auth - INFO:553818543 used the command /group_list
2021-03-16 18:48:51,421 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-23' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 76, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:48:57,781 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:48:57,785 aiogram - WARNING:Goodbye!
2021-03-16 18:50:49,034 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:50:50,235 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:50:50,240 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:50:51,698 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-9' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=IndexError('string index out of range')>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 246, in process_update
    return await self.message_handlers.notify(update.message)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 48, in attach_state
    await message.answer("List of your groups:",reply_markup=connect_button(group_list))
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/keyboards/choise_buttons.py", line 77, in connect_button
    text = g[0]+' - '+'headman.' if g[1] else g[0]+' - '+'member.'
IndexError: string index out of range
2021-03-16 18:51:10,509 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:51:10,512 aiogram - WARNING:Goodbye!
2021-03-16 18:52:13,730 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:52:15,064 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:52:15,069 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:52:22,169 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 64, in call_connect
    await call.message.answer(f'Вы присоеденились к группе: {message.text}\n'
NameError: name 'message' is not defined
2021-03-16 18:52:47,029 handlers.auth - INFO:553818543 used the command /group_list
2021-03-16 18:52:52,237 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-29' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 64, in call_connect
    await call.message.answer(f'Вы присоеденились к группе: {message.text}\n'
NameError: name 'message' is not defined
2021-03-16 18:53:01,670 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:53:01,674 aiogram - WARNING:Goodbye!
2021-03-16 18:55:11,943 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:55:13,181 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:55:13,186 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:55:15,868 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 66, in call_connect
    logger.info('%s changed the group to: %s', message.chat.id,message.text)
NameError: name 'message' is not defined
2021-03-16 18:55:28,726 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:55:28,730 aiogram - WARNING:Goodbye!
2021-03-16 18:56:15,094 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:56:16,521 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:56:16,524 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:56:19,229 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-15' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/auth.py", line 66, in call_connect
    logger.info('%s changed the group to: %s', message.chat.id,message.text)
NameError: name 'message' is not defined
2021-03-16 18:56:49,822 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 18:56:49,825 aiogram - WARNING:Goodbye!
2021-03-16 18:58:05,256 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 18:58:05,472 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 18:58:05,477 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 18:58:07,910 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 18:58:16,365 handlers.member - INFO:553818543 used the command /help
2021-03-16 18:58:18,603 handlers.member - INFO:553818543 found out the schedule
2021-03-16 18:58:27,307 handlers.member - INFO:553818543 found out the schedule
2021-03-16 18:58:30,008 handlers.member - INFO:553818543 found out the schedule
2021-03-16 18:59:49,441 handlers.auth - INFO:553818543 changed the group to: ИБ
2021-03-16 18:59:52,518 handlers.member - INFO:553818543 used the command /help
2021-03-16 18:59:55,510 handlers.member - INFO:553818543 used the command /subjects
2021-03-16 19:00:06,533 handlers.auth - INFO:553818543 changed the group to: ИБ
2021-03-16 19:00:09,407 handlers.member - INFO:553818543 used the command /help
2021-03-16 19:00:20,135 handlers.member - INFO:553818543 leave_group: ИБ
2021-03-16 19:01:11,283 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 19:01:11,484 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:12,663 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 19:01:12,667 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 19:01:16,640 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:18,423 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 19:01:21,798 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:26,926 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:32,073 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:37,205 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:42,307 aiogram.dispatcher.dispatcher - ERROR:Cause exception while getting updates.
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 359, in start_polling
    updates = await self.bot.get_updates(limit=limit, offset=offset, timeout=timeout)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/utils/exceptions.py", line 139, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
2021-03-16 19:01:45,006 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 19:01:45,009 aiogram - WARNING:Goodbye!
2021-03-16 19:01:48,638 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 19:01:48,640 aiogram - WARNING:Goodbye!
2021-03-16 19:01:56,936 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 19:01:58,460 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 19:01:58,462 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 19:02:00,769 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 19:02:03,027 handlers.member - INFO:553818543 used the command /help
2021-03-16 19:02:10,440 handlers.member - INFO:553818543 found out the schedule
2021-03-16 19:02:12,466 handlers.member - INFO:553818543 found out the schedule
2021-03-16 19:02:14,972 handlers.member - INFO:553818543 found out the schedule
2021-03-16 19:02:20,885 handlers.auth - INFO:553818543 changed the group to: Лол
2021-03-16 19:02:23,453 handlers.member - INFO:553818543 used the command /help
2021-03-16 19:02:36,028 handlers.member - INFO:553818543 used the command /group_name
2021-03-16 19:02:47,168 handlers.auth - INFO:553818543 changed the group to: Абдула
2021-03-16 19:02:54,371 handlers.member - INFO:553818543 leave_group: Абдула
2021-03-16 19:03:03,150 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 19:25:15,192 handlers.auth - INFO:665754238 changed the group to: ИБ 2 курс
2021-03-16 19:25:43,138 handlers.member - INFO:665754238 found out the schedule
2021-03-16 20:05:04,899 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 20:05:08,740 handlers.member - INFO:553818543 used the command /help
2021-03-16 20:05:15,488 handlers.member - INFO:553818543 learned homework
2021-03-16 20:05:25,316 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-317' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/member.py", line 171, in del_hw
    logger.info('%s deleted homework',message.chat.id)
NameError: name 'message' is not defined
2021-03-16 20:05:45,565 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-320' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/member.py", line 171, in del_hw
    logger.info('%s deleted homework',message.chat.id)
NameError: name 'message' is not defined
2021-03-16 20:05:55,124 handlers.member - INFO:553818543 learned homework
2021-03-16 20:05:56,965 asyncio - ERROR:Task exception was never retrieved
future: <Task finished name='Task-328' coro=<Dispatcher._process_polling_updates() done, defined at /data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py:380> exception=NameError("name 'message' is not defined")>
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 388, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 225, in process_updates
    return await asyncio.gather(*tasks)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/venv/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File "/data/data/com.termux/files/home/test-server/HEADMAN_BOT/handlers/member.py", line 171, in del_hw
    logger.info('%s deleted homework',message.chat.id)
NameError: name 'message' is not defined
2021-03-16 20:08:34,358 aiogram.dispatcher.dispatcher - INFO:Stop polling...
2021-03-16 20:08:34,361 aiogram - WARNING:Goodbye!
2021-03-16 20:08:44,505 aiogram - INFO:Bot: HEADMAN_BOT [@DSU_HEADMAN_BOT]
2021-03-16 20:08:45,913 aiogram - WARNING:Updates were skipped successfully.
2021-03-16 20:08:45,917 aiogram.dispatcher.dispatcher - INFO:Start polling.
2021-03-16 20:08:59,260 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 20:09:02,188 handlers.member - INFO:553818543 used the command /help
2021-03-16 20:09:09,579 handlers.member - INFO:553818543 learned homework
2021-03-16 20:09:11,214 handlers.member - INFO:553818543 deleted homework
2021-03-16 20:11:32,289 handlers.headman - INFO:553818543 created a new homework with files
2021-03-16 20:11:43,865 handlers.member - INFO:553818543 learned homework
2021-03-16 20:57:52,718 handlers.auth - INFO:1037171446 changed the group to: ИБ 2 курс
2021-03-16 20:58:10,901 handlers.auth - INFO:1037171446 changed the group to: ИБ 2 курс
2021-03-16 21:32:50,386 handlers.auth - INFO:553818543 changed the group to: ИБ 2 курс
2021-03-16 22:54:25,429 handlers.auth - INFO:540553756 changed the group to: ИБ 2 курс
2021-03-16 22:54:28,261 handlers.member - INFO:540553756 used the command /help
2021-03-16 22:54:31,549 handlers.member - INFO:540553756 found out the schedule
2021-03-17 01:02:13,044 handlers.member - INFO:553818543 found out the schedule
2021-03-17 01:02:19,505 handlers.member - INFO:553818543 found out the schedule
2021-03-17 01:39:31,945 handlers.auth - INFO:983872632 changed the group to: ИБ 2 курс
2021-03-17 01:39:35,487 handlers.member - INFO:983872632 used the command /help
2021-03-17 01:39:37,755 handlers.member - INFO:983872632 found out the schedule
2021-03-17 02:01:19,385 handlers.member - INFO:553818543 found out the schedule
2021-03-17 02:03:46,221 handlers.member - INFO:553818543 found out the schedule
2021-03-17 02:04:12,341 handlers.member - INFO:553818543 found out the schedule
2021-03-17 02:06:30,556 handlers.member - INFO:553818543 found out the schedule
2021-03-17 14:47:30,115 handlers.member - INFO:983872632 found out the schedule
2021-03-17 14:47:35,688 handlers.member - INFO:983872632 found out the schedule
